config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :goals, only: [:new, :create, :show] do
    member do
      patch 'complete'
    end
  end
  resources :comments, only: :create
  resources :cheers, only: :create
end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  validates :goal_id, :user_id, presence: true
  validate :daily_cheer_limit

  belongs_to :user
  belongs_to :goal

  private

  def daily_cheer_limit
    user = User.find(self.user_id)
    unless user.cheers_made_today < User::DAILY_CHEER_LIMIT
      errors.add(:base, "#{user.username} is out of cheers.")
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :author_id, :commentable_id,
    :commentable_type, presence: true

  belongs_to :author, class_name: "User", foreign_key: :author_id
  belongs_to :commentable, polymorphic: true
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  content    :string           not null
#  author_id  :integer          not null
#  private    :boolean          default(FALSE), not null
#  completed  :boolean          default(FALSE), not null
#  created_at :datetime
#  updated_at :datetime
#

class Goal < ActiveRecord::Base
  validates :author_id, :content, presence: true
  validates :private, :completed, inclusion: [true, false]

  belongs_to :author, class_name: "User", foreign_key: :author_id

  has_many :comments, as: :commentable

  has_many :cheers

  after_initialize :set_default

  def cheer_count
    self.cheers.count
  end

  private

  def set_default
    self.completed ||= FALSE
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

require 'BCrypt'

class User < ActiveRecord::Base
  DAILY_CHEER_LIMIT = 5

  attr_reader :password
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :goals, class_name: "Goal", foreign_key: :author_id

  has_many :comments, as: :commentable

  has_many :authored_comments, class_name: "Comment", foreign_key: :author_id

  has_many :cheers

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!

    self.session_token
  end

  def cheers_made_today
    self.cheers.where(created_at: Date.today).count
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user_id

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user_id
    @current_user_id ||= current_user ? current_user.id : nil
  end

end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController
  def create
    @cheer = current_user.cheers.new(cheer_params)
    if @cheer.save
      redirect_to user_url(@cheer.goal.author)
    else
      flash[:errors] = @cheer.errors.full_messages
      redirect_to user_url(@cheer.goal.author)
    end
  end

  private

  def cheer_params
    params.require(:cheer).permit(:goal_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.authored_comments.new(comment_params)

    unless @comment.save
      flash[:errors] = @comment.errors.full_messages
    end

    if @comment.commentable_type == "User"
      redirect_to user_url(@comment.commentable_id)
    else
      redirect_to goal_url(@comment.commentable_id)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_login, only: :show

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    @goal.save
    flash[:errors] = @goal.errors.full_messages
    redirect_to user_url(current_user)
  end

  def complete
    @goal = current_user.goals.find(params[:id])
    @goal.update!(completed: true)
    flash[:errors] = @goal.errors.full_messages
    redirect_to user_url(current_user)
  end

  def show
    @goal = Goal.find(params[:id])
  end

  private

  def goal_params
    params.require(:goal).permit(:content, :private)
  end

  def require_login
    unless current_user
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_status(goal)
    goal.completed? ? "completed" : "not yet completed" 
  end
end

app/views/comments/_form.html.erb
<% if current_user %>

<form action="<%= comments_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[commentable_id]" value="<%= commentable_id%>">
  <input type="hidden" name="comment[commentable_type]" value="<%= commentable_type%>">

  <label>Comment
    <textarea name="comment[body]"></textarea>
  </label>

  <button>Add Comment</button>
</form>

<% end %>

app/views/comments/_show.html.erb
<% if commentable.comments.present? %>
  <ul>
    <% commentable.comments.each do |comment| %>
      <li><%= comment.body %></li>
    <% end %>
  </ul>
<% end %>

app/views/goals/_completed_button.html.erb
<form action="<%= complete_goal_url(goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <button>Completed</button>
</form>

app/views/goals/_form.html.erb
<% if user == current_user %>

  <form action="<%= goals_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

    <label>
      Goal
      <input type="text" name="goal[content]">
    </label>

    <label>
      Public
      <input type="radio" name="goal[private]" value="false">
    </label>

    <label>
      Private
      <input type="radio" name="goal[private]" value="true">
    </label>

    <button>Add Goal</button>
  </form>

<% end %>

app/views/goals/_show.html.erb
<% if user.goals %>
Goals
<ul>
  <% user.goals.each do |goal| %>
    <% next if goal.private? && goal.author_id != current_user_id %>
    <li>
      <form action="<%= cheers_url%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

        <input type="hidden" name="cheer[goal_id]" value="<%= goal.id %>">

        <button>Cheer</button>
      </form>

      <%= goal.cheer_count %> cheer(s)



      <a href="<%= goal_url(goal)%>"><%= goal.content %></a>,
       created at <%= goal.created_at %> status: <%= display_status(goal)%>
       <% if !goal.completed? && goal.author_id == current_user_id %>
        <%= render "goals/completed_button", goal: goal %>
       <% end %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/goals/show.html.erb
<%= @goal.author.username %>'s Goal
<%= @goal.content %>

<%= render "comments/show", commentable: @goal %>

<%= render "comments/form", commentable_id: @goal.id, commentable_type: "Goal"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  Hi, <%= current_user.username %>
  <form action="<%= session_url %>" method="POST">
    <input
      type="hidden"
      name="_method"
      value="DELETE">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <button>Sign Out</button>
  </form>

<% end %>


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url%>" method="post">
  <input type="hidden" name="authenticity_token" method="<%= form_authenticity_token%>">

  <label>
    Username
    <input type="text" name="user[username]">
  </label>

  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <button>Sign Up</button>
</form> 

app/views/users/show.html.erb
<%= @user.username %>'s Page

<%= render "comments/form", commentable_id: @user.id, commentable_type: "User" %>

<%= render "comments/show", commentable: @user %>

<%= render "goals/form", user: @user%>

<%= render "goals/show", user: @user %>